---
- hosts: all
  sudo: true
  tasks:
    #################INSTALL DOCKER
    - name: update apt cache
      apt: update_cache=yes

    - name: install cacertificates and apt-transport-https
      apt: name=apt-transport-https state=present
      apt: name=ca-certificates state=present

    - name: add docker repo key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: create file docker deb
      file: path=/etc/apt/sources.list.d/ state=directory mode=0655
      file: path=/etc/apt/sources.list.d/docker.list state=touch mode=0655

    - name: insert deb in docker file
      lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty testing"

    - name: update apt cache
      apt: update_cache=yes

    #Not working
    # - name: purge previous version
    #   apt: name=lxc-docker purge=yes

    - name: update apt cache
      apt: update_cache=yes

    - name: install recommanded packages
      apt: name=linux-image-extra-3.13.0-85-generic state=present

    - name: install docker engine
      apt: name=docker-engine state=present
    ################################################

    - name: run docker
      service: name=docker state=reloaded

    - command: docker --version
      register: dockerV
    - debug: var=dockerV.stdout_lines
